[[mgr.prepend_keymap]]
on = ["<F3>"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["F"]
run = '''
shell 'fd --type f . | fzf --preview "bat --style=numbers --color=always {}" --height 80% --layout=reverse | xargs -r yazi' --block
'''
desc = "Search file by name via fd+fzf"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"


[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["<Backspace>"]
run = "leave"
desc = "Go up one level"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to root of git repository"

[[mgr.prepend_keymap]]
on   = [ "g", "C" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"


[[mgr.append_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = ["<A-Left>"]
run = "back"
desc = "Go back to previous directory"

[[mgr.prepend_keymap]]
on = ["<A-Right>"]
run = "forward"
desc = "Go forward"


[[mgr.prepend_keymap]]
on = [ "c", "F"]
run = "plugin copy-file-contents"
desc = "Copy contents of file"

[[mgr.append_keymap]]
on = [ "c", "r" ]
run = "plugin path-from-root"
desc = "Copies path from git root"


[[mgr.prepend_keymap]]
on   = [ "g", "g" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.claude"
desc = "~/.claude"

[[mgr.prepend_keymap]]
on   = [ "g", "b" ]
run  = "cd /c/work/projects/altisima-central-vault/__home/projects/ai/brain/"
desc = "Go to brain directory"

[[mgr.prepend_keymap]]
on   = [ "g", "b" ]
run  = "cd /c/work/projects/altisima-central-vault/__home/projects/ai/brain/"
desc = "Go to brain directory"

[[mgr.prepend_keymap]]
on   = [ "g", "f" ]
run  = "cd /home/jarda/k3w-docker/src/web-frontend/apps/web"
desc = "Go to brain directory"

# bookmarks

[[mgr.prepend_keymap]]
on = "["
run = "plugin whoosh jump_by_key"
desc = "Jump bookmark by key"

# Direct fuzzy search access
[[mgr.prepend_keymap]]
on = "}"
run = "plugin whoosh fuzzy"
desc = "Direct fuzzy search for bookmarks"

# Basic bookmark operations
[[mgr.prepend_keymap]]
on = [ "]", "a" ]
run = "plugin whoosh save"
desc = "Add bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "A" ]
run = "plugin whoosh save_cwd"
desc = "Add bookmark (current directory)"

# Temporary bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "t" ]
run = "plugin whoosh save_temp"
desc = "Add temporary bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "T" ]
run = "plugin whoosh save_cwd_temp"
desc = "Add temporary bookmark (current directory)"

# Jump to bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "f" ]
run = "plugin whoosh jump_by_fzf"
desc = "Jump bookmark by fzf"

# Delete bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "d" ]
run = "plugin whoosh delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "D" ]
run = "plugin whoosh delete_by_fzf"
desc = "Delete bookmarks by fzf (use TAB to select multiple)"

[[mgr.prepend_keymap]]
on = [ "]", "C" ]
run = "plugin whoosh delete_all"
desc = "Delete all user bookmarks"

# Rename bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "r" ]
run = "plugin whoosh rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "R" ]
run = "plugin whoosh rename_by_fzf"
desc = "Rename bookmark by fzf"

## VS CODE

[[mgr.prepend_keymap]]
on  = ["o"]
run = "shell 'code \"$PWD\" \"$0\"' --block"
desc = "Open current directory in VS Code"

# find by char

[[mgr.prepend_keymap]]
on   = "`"
run  = "plugin jump-to-char"
desc = "Jump to char"


[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

# [[mgr.prepend_keymap]]
# on   = "f"
# run  = "plugin smart-filter"
# desc = "Smart filter"

