[[mgr.prepend_keymap]]
on = ["<F3>"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["F"]
run = '''
shell 'fd --type f . ~ | fzf --preview "bat --style=numbers --color=always {}" --height 80% --layout=reverse | xargs -r yazi' --block
'''
desc = "Search file by name via fd+fzf"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"


[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["<Backspace>"]
run = "leave"
desc = "Go up one level"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to root of git repository"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

[[mgr.append_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = ["<A-Left>"]
run = "back"
desc = "Go back to previous directory"

[[mgr.prepend_keymap]]
on = ["<A-Right>"]
run = "forward"
desc = "Go forward"


[[mgr.prepend_keymap]]
on = [ "c", "F"]
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.append_keymap]]
on = [ "c", "r" ]
run = "plugin path-from-root"
desc = "Copies path from git root"


[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

# bookmarks

[[mgr.prepend_keymap]]
on = [ "b", "s" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "B" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"
