# yazi.toml
[mgr]
# show_hidden = true
ratio = [1,3,4]

[preview.mime_rules]

[preview]
ext_rules = [
 { ext = "md", mime = "text/markdown" }
]

[plugin]
prepend_previewers = [	
	# PDF files - text preview
	{ mime = "application/pdf", run = 'piper -- pdftotext -l 3 "$1" - 2>/dev/null || file -b "$1"' },
	
	# HTML files - clean text output
	{ mime = "text/html", run = 'piper -- w3m -dump "$1" 2>/dev/null || lynx -dump "$1" 2>/dev/null || cat "$1"' },
	
	# DOC/DOCX files
	{ mime = "application/msword", run = 'piper -- pandoc "$1" -t plain 2>/dev/null || file -b "$1"' },
	{ mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", run = 'piper -- pandoc "$1" -t plain 2>/dev/null || file -b "$1"' },
	
	# Binary executable files - file info summary
	{ mime = "application/x-executable", run = 'piper -- file -b "$1"' },
	{ mime = "application/x-sharedlib", run = 'piper -- file -b "$1"' },
	{ mime = "application/x-pie-executable", run = 'piper -- file -b "$1"' },
	{ mime = "application/octet-stream", run = 'piper -- file -b "$1"' },

	# Markdown with glow via piper
	# Options: -s auto/dark/light, -w width, -p pager mode
	{ name = "*.md", run = 'piper -- ~/go/bin/glow -s auto "$1"' },
	
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/vnd.rar",         run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/x-zstd",          run = "ouch" },
	{ mime = "application/zstd",            run = "ouch" },
	{ mime = "application/java-archive",    run = "ouch" },

	# Debian packages - show package info and contents
	{ mime = "application/vnd.debian.binary-package", run = 'piper -- dpkg-deb -I "$1" && echo "\\n--- Contents ---" && dpkg-deb -c "$1"' },
	{ name = "*.deb", run = 'piper -- dpkg-deb -I "$1" && echo "\\n--- Contents ---" && dpkg-deb -c "$1"' },
	
	# ZSync files - show metadata
	{ name = "*.zsync", run = 'piper -- head -20 "$1" | grep -E "^[A-Za-z-]+:" || file -b "$1"' },

	# Directory previewer  
	{ name = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },

]

# Fallback for unrecognized files - append instead of prepend to not override built-in image preview
append_previewers = [
	# Binary files fallback - show file info instead of bat warnings
	{ name = "*", run = 'piper -- (file -b "$1" | grep -qi "text\\|script\\|source" && bat -p --color=always "$1" || file -b "$1")' },
]
