# yazi.toml
[mgr]
# show_hidden = true
ratio = [1,3,4]

[preview.mime_rules]

[preview]
ext_rules = [
 { ext = "md", mime = "text/markdown" }
]

[plugin]
prepend_previewers = [	
	# Markdown with glow via piper
	# Options: -s auto/dark/light, -w width, -p pager mode
	{ name = "*.md", run = 'piper -- ~/go/bin/glow -s auto "$1"' },
	
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/vnd.rar",         run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/x-zstd",          run = "ouch" },
	{ mime = "application/zstd",            run = "ouch" },
	{ mime = "application/java-archive",    run = "ouch" },

	# Default file previewer
	{ name = "*", run = 'piper -- bat -p --color=always "$1"' },
	
	# Directory previewer  
	{ name = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },

]
